/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonproject;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pbyra
 */
public class InvWin extends javax.swing.JFrame {
    private DefaultListModel model;

    /**
     * Creates new form InvWin
     */
    public InvWin() {
        initComponents();
               
        
         // PokemonProject.player.inventory.add(potion);
        
        model = new DefaultListModel();
        invList.setModel(model);

        for(Item item : PokemonProject.player.inventory){
            model.addElement(item.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invList = new javax.swing.JList<>();
        inspectBtn = new javax.swing.JButton();
        dropBtn = new javax.swing.JButton();

        invList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(invList);

        inspectBtn.setText("Inspect");
        inspectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspectBtnActionPerformed(evt);
            }
        });

        dropBtn.setText("Drop");
        dropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(dropBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(inspectBtn)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inspectBtn)
                    .addComponent(dropBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBtnActionPerformed
        PokemonProject.player.inventory.remove(invList.getSelectedIndex());        // TODO add your handling code here:
    }//GEN-LAST:event_dropBtnActionPerformed

    private void inspectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspectBtnActionPerformed
        Object[] hey = { "Use", "Back",};
        int itemChoice = JOptionPane.showOptionDialog(null, invList.getSelectedValue(), invList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, hey, 0);
        switch (itemChoice) {
            case 0: 
                if (invList.getSelectedValue() == "Potion") {
                    PokemonProject.player.getHealedPotion();
                    int healthVal = PokemonProject.player.getEnergy();
                    NewJFrame.healthLabel.setText(String.valueOf(healthVal));
                    break;
                }
                if (invList.getSelectedValue() == "Oran Berry") {
                    PokemonProject.player.getHealedBerry();
                    int healthVal = PokemonProject.player.getEnergy();
                    NewJFrame.healthLabel.setText(String.valueOf(healthVal));
                    break;
                }
                if (invList.getSelectedValue() == "Old Plush") {
                    JOptionPane.showMessageDialog(null, PokemonProject.plush.getDesc());
                    break;
                }
                if (invList.getSelectedValue() == "Baseball") {
                    JOptionPane.showMessageDialog(null, PokemonProject.baseball.getDesc());
                    break;
                }
            case 1:
                break;
        }
    }//GEN-LAST:event_inspectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dropBtn;
    private javax.swing.JButton inspectBtn;
    private javax.swing.JList<String> invList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
