/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonproject;
import static com.mycompany.pokemonproject.PokemonProject.player;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pbyra
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        int healthVal = PokemonProject.player.getEnergy();
        healthLabel.setText(String.valueOf(healthVal));
        storyscreen.setText(player.location.text);
        setTitle(player.location.name);
    }
    // code from https://www.youtube.com/watch?v=EluNyKun6Lk&t=48s
    void updateOutput(int roomNumber) {
        String temp;
        if (roomNumber == Path.NoPath) {
            temp = "You can't go that way!";
        }
        else {
            Room r = PokemonProject.getPlayer().getRoom();
        }
        storyscreen.setText(player.location.text);
    }
    // code ends
    
       


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        westButton = new javax.swing.JButton();
        northButton = new javax.swing.JButton();
        eastButton = new javax.swing.JButton();
        southButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        storyscreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new Font("Ariel", Font.PLAIN, 20));
        jLabel2.setText("Energy:");

        healthLabel.setFont(new Font("Ariel", Font.PLAIN, 20));

        westButton.setText("West");
        westButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westButtonActionPerformed(evt);
            }
        });

        northButton.setText("North");
        northButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northButtonActionPerformed(evt);
            }
        });

        eastButton.setText("East");
        eastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastButtonActionPerformed(evt);
            }
        });

        southButton.setText("South");
        southButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Interact");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bag");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        storyscreen.setFont(new Font("Ariel", Font.PLAIN, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storyscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(westButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(southButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(northButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eastButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(healthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storyscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(healthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eastButton)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(westButton)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(northButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(southButton)
                            .addComponent(jButton2))
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void westButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westButtonActionPerformed
        updateOutput(PokemonProject.movePlayerTo(Path.WEST));
        if (PokemonProject.player.location.getN() == -1) {
            northButton.setEnabled(false);
        }
        else {
            northButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getS() == -1) {
            southButton.setEnabled(false);
        }
        else {
            southButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getW() == -1) {
            westButton.setEnabled(false);
        }
        else {
            westButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getE() == -1) {
            eastButton.setEnabled(false);
        }
        else {
            eastButton.setEnabled(true);
        }
    }//GEN-LAST:event_westButtonActionPerformed

    private void northButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northButtonActionPerformed
        updateOutput(PokemonProject.movePlayerTo(Path.NORTH));
        if (PokemonProject.player.location.getN() == -1) {
            northButton.setEnabled(false);
        }
        else {
            northButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getS() == -1) {
            southButton.setEnabled(false);
        }
        else {
            southButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getW() == -1) {
            westButton.setEnabled(false);
        }
        else {
            westButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getE() == -1) {
            eastButton.setEnabled(false);
        }
        else {
            eastButton.setEnabled(true);
        }
    }//GEN-LAST:event_northButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] itemPot = { "Take Item", "Leave It",};
        if (player.location == PokemonProject.map.get(2)) {
            ImageIcon icon = new ImageIcon("Potion.png");
            Image potionPic = icon.getImage();
            Image scaledpotionPic = potionPic.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledpotionPic);
                int itemResponse = JOptionPane.showOptionDialog(null, PokemonProject.potion.getDesc(), PokemonProject.potion.getName(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, itemPot, 0);
                switch (itemResponse) {
                    case 0:
                        PokemonProject.player.inventory.add(PokemonProject.potion);
                        break;
                        
                    case 1:
                        break;
                }
                
            }
        if (player.location == PokemonProject.map.get(4)) {
            ImageIcon icon = new ImageIcon("Oranberry.png");
            Image oranPic = icon.getImage();
            Image scaledoranPic = oranPic.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledoranPic);
                int itemResponse = JOptionPane.showOptionDialog(null, PokemonProject.oranberry.getDesc(), PokemonProject.oranberry.getName(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, itemPot, 0);
                switch (itemResponse) {
                    case 0:
                        PokemonProject.player.inventory.add(PokemonProject.oranberry);
                        break;
                        
                    case 1:
                        break;
                }
                
            }
        if (player.location == PokemonProject.map.get(5)) {
            ImageIcon icon = new ImageIcon("Plush.png");
            Image plushPic = icon.getImage();
            Image scaledplushPic = plushPic.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledplushPic);
                int itemResponse = JOptionPane.showOptionDialog(null, PokemonProject.plush.getDesc(), PokemonProject.plush.getName(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, itemPot, 0);
                switch (itemResponse) {
                    case 0:
                        PokemonProject.player.inventory.add(PokemonProject.plush);
                        break;
                        
                    case 1:
                        break;
                }
                
            }
        if (player.location == PokemonProject.map.get(12)) {
            ImageIcon icon = new ImageIcon("Baseball1.png");
            Image baseballPic = icon.getImage();
            Image scaledbaseballPic = baseballPic.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledbaseballPic);
                int itemResponse = JOptionPane.showOptionDialog(null, PokemonProject.baseball.getDesc(), PokemonProject.baseball.getName(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, itemPot, 0);
                switch (itemResponse) {
                    case 0:
                        PokemonProject.player.inventory.add(PokemonProject.baseball);
                        break;
                        
                    case 1:
                        break;
                }
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void southButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southButtonActionPerformed
        updateOutput(PokemonProject.movePlayerTo(Path.SOUTH));
        if (PokemonProject.player.location.getN() == -1) {
            northButton.setEnabled(false);
        }
        else {
            northButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getS() == -1) {
            southButton.setEnabled(false);
        }
        else {
            southButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getW() == -1) {
            westButton.setEnabled(false);
        }
        else {
            westButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getE() == -1) {
            eastButton.setEnabled(false);
        }
        else {
            eastButton.setEnabled(true);
        }
    }//GEN-LAST:event_southButtonActionPerformed

    private void eastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastButtonActionPerformed
        updateOutput(PokemonProject.movePlayerTo(Path.EAST));
        if (PokemonProject.player.location.getN() == -1) {
            northButton.setEnabled(false);
        }
        else {
            northButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getS() == -1) {
            southButton.setEnabled(false);
        }
        else {
            southButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getW() == -1) {
            westButton.setEnabled(false);
        }
        else {
            westButton.setEnabled(true);
        }
        if (PokemonProject.player.location.getE() == -1) {
            eastButton.setEnabled(false);
        }
        else {
            eastButton.setEnabled(true);
        }
    }//GEN-LAST:event_eastButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new InvWin().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton eastButton;
    protected static javax.swing.JLabel healthLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    protected static javax.swing.JButton northButton;
    protected static javax.swing.JButton southButton;
    protected static javax.swing.JLabel storyscreen;
    protected static javax.swing.JButton westButton;
    // End of variables declaration//GEN-END:variables
}
